### ISSUE TITLE
Installing following the README's instructions fails

### ISSUE THREAD

**Issue by ruurtjan** [kitlangton/zio-magic#10]
Hi Kit,

When I gave ZIO-magic a spin, I noticed that the README said to install with `"io.github.kitlangton" % "zio-magic" % "0.1.7",` instead of `"io.github.kitlangton" %% "zio-magic" % "0.1.7",`. The first fails, but the latter succeeds. Presumably because uploading to maven central might not be configured correctly, or the readme might just be incorrect.

Note that mvnrepository.com also has issues finding some versions of ZIO-magic.
https://mvnrepository.com/artifact/io.github.kitlangton/zio-magic

**Comment by kitlangton** [comment]
Oh! Thanks for the report! Yeah, that's just a typo—I need to add that second `%` in there! Thanks for the issue. 

As far as `mvnrepository` goes, I believe its indexing is delayed by ~24 hours or so. Everything seems to show up there eventually :)
