### ISSUE TITLE
Magic for ZStream

### ISSUE THREAD

**Issue by cipriansofronia** [kitlangton/zio-magic#103]
It would be nice to have `.inject` and friends for streams as well. 
Please close this if it's already baked into ZIO 2.0 😅 
Thank you for this great lib! 🙇🏻

**Comment by kitlangton** [comment]
<img width="680" alt="image" src="https://user-images.githubusercontent.com/7587245/129369108-91aab9af-fe67-4211-9d79-d613ad543ec7.png">
🥳 
Yup! All baked into ZIO 2.0 😄
