### ISSUE TITLE
Can't wire if have several implementations of same Foo[F[_]]

### ISSUE THREAD

**Issue by Space-hero** [kitlangton/zio-magic#111]
As it seems, we can't wire all components, if inside braces we have several layers for different F's in Foo:
https://scastie.scala-lang.org/L481koRoTX6TevvIIpAOcg

**Comment by kitlangton** [comment]
Ah, instead of:
```scala
val magicLayer:RLayer[Has[A],Has[Foo[UIO]]] = ZLayer.wireSome[Has[A],Has[Foo[UIO]]] {
  layerBaz
  layerBar
}
```
You need to write it like this: 😄 
```scala
val magicLayer:RLayer[Has[A],Has[Foo[UIO]]] = ZLayer.wireSome[Has[A],Has[Foo[UIO]]](
  layerBaz,
  layerBar
)
```

**Comment by kitlangton** [comment]
Also, with ZIO 2.0, `inject` and `wire` are built in :), so you can do this: https://scastie.scala-lang.org/Qze6pZ2oQWaEZQaHJQLteQ
