### ISSUE TITLE
Magic partial layer

### ISSUE THREAD

**Issue by Esardes** [kitlangton/zio-magic#13]
I would like to be able to write:
```
type Requirements = ???
type LayerOutput = T1 with T2

val result: ZLayer[Requirements,Throwable,LayerOutput] = ZLayer.fromMagic[Requirements, Throwable, LayerOutput] (
  T1.live, //needs Requirements to build
  T2.live
)
```

**Comment by kitlangton** [comment]
Thanks for the suggestion! That's a great idea.

I could also list out the missing services when using the normal `ZLayer.fromMagic[Output]` constructor, so the user could copy-paste the remaining requirements from the compile error and swap in this two-parameter overload.

The one concern would be having a confusing number of options to choose from. I'm hoping to figure out the maximally useful subset of all possible methods. But this seems like a very reasonable candidate. If you're able, could you expand on the context wherein this would be useful? Depending on the situation, the non-macro `++` operator behaves similarly, as it gathers the requirements from both arguments. Though, anytime one uses `>>>` one must fully satisfy the requirements of the ZLayer on the right hand side.

**Comment by kitlangton** [comment]
I'm going to give it a whirl though :)

**Comment by octavz** [comment]
I came here to ask for same feature :), would be indeed very cool to have partial layer building.

**Comment by kitlangton** [comment]
@octavz @Esardes Your hero has arrived (in @senia-psm)!
I'll push to maven this evening :)

**Comment by senia-psm** [comment]
@kitlangton would you like some help with configuring publishing to maven from github actions? It allows you to publish a new version by creating a new tag.

**Comment by kitlangton** [comment]
That would be amazing @senia-psm :)

**Comment by senia-psm** [comment]
@kitlangton let's discuss it here: #17
I can't configure it for you - you have to add your credentials to github secrets.
