### ISSUE TITLE
Scala 3 artifact

### ISSUE THREAD

**Issue by soujiro32167** [kitlangton/zio-magic#130]
```
[error] (partial-registration-server / update) sbt.librarymanagement.ResolveException: Error downloading io.github.kitlangton:zio-magic_3:0.3.11
[error]   Not found
[error]   Not found
[error]   not found: /Users/ekasik/.ivy2/local/io.github.kitlangton/zio-magic_3/0.3.11/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/io/github/kitlangton/zio-magic_3/0.3.11/zio-magic_3-0.3.11.pom
```
=[

**Comment by kitlangton** [comment]
Currently this implementation lives in ZIO 2.0. and I don't have enough at the moment to port it (prepping for conference and ZIO 2.0 and the day job 😄), though if anyone wants it for ZIO 1.0, I'd happily merge a PR.

**Comment by soujiro32167** [comment]
My mistake: I saw a [scala 3 in the build](https://github.com/kitlangton/zio-magic/blob/master/build.sbt#L4) and assumed this compiled/released against scala 3 x_x

Good luck with the conference! Excited to see what you come up with =]

**Comment by kitlangton** [comment]
:D I think that was placed there aspirationally at some point. Thanks for understanding! 😄 I should add a note to the Readme for now
