### ISSUE TITLE
Magic for ZManaged

### ISSUE THREAD

**Issue by heaven-born** [kitlangton/zio-magic#14]
zio-magic is an extremely helpful! I would love to have the same magic for `ZManaged`. Converting `ZManaged` to `ZIO` in order to provide Env. is not always an option.

**Comment by kitlangton** [comment]
Oh! Duh! I seldom use ZManaged directly, so I completely forgot about it. Thanks for reminding me :)

**Comment by kitlangton** [comment]
I should do the same with ZStreams now that I think about it.

**Comment by kitlangton** [comment]
These will be implemented in the work for ZIO 2.0, but just going to recommend using `ZLayer.wire` for now and passing in the generated layer.
