### ISSUE TITLE
Configure publishing with github actions

### ISSUE THREAD

**Issue by senia-psm** [kitlangton/zio-magic#17]
Configure publishing as described here: https://github.com/olafurpg/sbt-ci-release

See this PR for example: https://github.com/senia-psm/zio-test-akka-http/pull/7/files

Basically all you have to do is to add your sonatype credentials and PGP key to github secrets.

After that all you have to do to publish a new version `A.B.C` is to create a tag `vA.B.C`

**Comment by kitlangton** [comment]
Thank you so much. I'm going to give this ago over the weekend. 
Currently simultaneously working and preparing for a conference talk I have to give tomorrow morning, so apologies for my slow responses 😅 But this is going to be _so_ much nicer than manual deploys. I always wondered how some projects deployed the SNAPSHOTs with commit hashes.

**Comment by senia-psm** [comment]
Np. If you have any questions - I will be happy to help. Unfortunately I can't make these changes as a PR - it involves your credentials.

**Comment by senia-psm** [comment]
@kitlangton if you are ok with giving me a user token for your sonatype account together with access to github secrets for this repo (for a day or less)  and publishing artefacts with pgp signature generated by me - I can configure publishing.

**Comment by kitlangton** [comment]
I think I got this all working finally :D Thanks for your initial push, @senia-psm!
