### ISSUE TITLE
Publish it

### ISSUE THREAD

**Issue by octavz** [kitlangton/zio-magic#2]
Hi,

This looks very cool and very useful for beginners and not only.
I am willing to give it a try and report back, we have a lot of ZIO code. 
This being a compile time feature, it can't do a lot of harm even if is not production ready so please publish it, otherwise is not usable.

BTW this is a very good idea, I don't know why others didn't think about earlier, layers are  quite difficult to combine when they start to pile up.

Thanks for your effort.

**Comment by jaredmdobson** [comment]
Yeah let me know if you need any help setting up github action workflow to publish it.

**Comment by kitlangton** [comment]
Luckily, I've already gone through the Sonatype account creation dance. So I think the next step is to open a *New Project* ticket, which I've done [here](https://issues.sonatype.org/browse/OSSRH-63533).

**Comment by kitlangton** [comment]
Though I do feel like one shouldn't be able to describe the setup as "easy" if it involves creating an account and issue upon a weird, semi-automatic Jira board 😝 
<img width="489" alt="image" src="https://user-images.githubusercontent.com/7587245/105085909-4e71e200-5a4d-11eb-9c5d-4f8639270303.png">

**Comment by jaredmdobson** [comment]
@kitlangton yeah for sure!  do you have a preferred communication tool? irc, slack, gitter, discord, you name it i'd be glad to talk you through it or just message you here. 👍🏿 really cool stuff 🔥

**Comment by kitlangton** [comment]
Thanks :) @jaredmdobson 

As the ZIO community's on discord, I've been using that lately. My account there is kit#1927 🎉  Looking forward to chatting!

**Comment by kitlangton** [comment]
@jaredmdobson @octavz 
Not fully published to Maven central. But I believe I've added a snapshot!? 😮 

Please bear with me as figure out the best way to get this to work 😄. That being said, let me know if this is totally broken for ya.

**Comment by octavz** [comment]
the snapshot works, I will open extra issues but for now it seems quite ok.

**Comment by kitlangton** [comment]
https://search.maven.org/artifact/io.github.kitlangton/zio-magic_2.13 👯
