### ISSUE TITLE
Missing 0.1.11 release for Scala 2.12

### ISSUE THREAD

**Issue by SelwynL** [kitlangton/zio-magic#38]
Noticed that for Scala 2.13 Nexus has version `0.1.11` available, however for Scala 2.12 Nexus only has version `0.1.10` as the latest: https://repo1.maven.org/maven2/io/github/kitlangton/zio-magic_2.12/

**Comment by kitlangton** [comment]
@SelwynL Good Catch! I forgot to type the `+` before the `publishSigned` command! Whoopsie. I'll get that out by tonight :)

**Comment by kitlangton** [comment]
@SelwynL Updated everything to `0.1.12` just because ;P

**Comment by kitlangton** [comment]
Let me know if you have any issues :)

**Comment by SelwynL** [comment]
Hurray! Loving zio-magic btw, it has already saved our ZIO projects some headaches!
