### ISSUE TITLE
Issues with debug formatting

### ISSUE THREAD

**Issue by sken77** [kitlangton/zio-magic#39]
Hi, we love this library and makes our life so much easier when dealing with Layers, but when debugging we ran into a wrapping issue

![image](https://user-images.githubusercontent.com/22631338/110988940-091fb180-8326-11eb-86fd-2209bcf5d0b1.png)

Manage to fix the formatting issue by copy pasting it to a text file and shifting everything below the first line to the right

![image](https://user-images.githubusercontent.com/22631338/110990412-25245280-8328-11eb-9b06-b1536c41d670.png)

Keep up the good work!

**Comment by kitlangton** [comment]
I believe I've fixed this in 0.2.0! Give it a whirl and let me know :)
