### ISSUE TITLE
[bug] provideMagicLayer / provideSomeMagicLayer evaluate arguments multiple times for the same type

### ISSUE THREAD

**Issue by nktpro** [kitlangton/zio-magic#44]
`provideMagicLayer` and `provideSomeMagicLayer` currently has a bug/limitation which they will evaluate the provided  argument expressions (the layers) multiple times (lazily) if the same type is a shared dependency of multiple other layers (or the effect itself).

Here's a reproducer:

```scala
import zio.magic._
import zio.{ExitCode, URIO, ZEnv, ZIO, ZLayer}

object ZioMagicBug extends zio.App {
  override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] = {
    val effect = for {
      intNumber <- ZIO.service[Int]
      doubleNumber <- ZIO.service[Double]
      longNumber <- ZIO.service[Long]
      _ <- zio.console.putStrLn(s"Int is $intNumber, Double is $doubleNumber and Long is $longNumber")
    } yield ()

    val layer1 = ZIO.service[Int].map(_.toDouble).toLayer
    val layer2 = ZIO.service[Int].map(_.toLong).toLayer

    effect
      .as(ExitCode(0))
      .provideMagicLayer(
        ZEnv.live,
        layer1,
        layer2, {
          println("This will be evaluated 3 times")
          ZLayer.succeed(123)
        }
      )
  }
}
```

Notice that the expression containing the `println` will be executed 3 times. In practice this led to creation of multiple instances of the same ZLayers, many of which are meant to be created exactly once during the entire lifecycle of an app.

**Comment by kitlangton** [comment]
Thanks for the report! I have actually fixed this issue in the code I've written in my PR against ZIO 2.0. Every layer passed into the method will be memoized. Obviously, it's also important to back port that functionality here. I've just been a bit busy working on the ZIO 2.0 integration. For the short term, I'd recommend pulling the layer definition into a `val` above where you use it, as you've done for `layer1` and `layer2`.

**Comment by kitlangton** [comment]
Alrighty! I back ported this goodness :) Layers passed into the macro methods will be automemoized! It's in `0.2.0`
