### ISSUE TITLE
Extract Spec related magic into separate module

### ISSUE THREAD

**Issue by vladimirkl** [kitlangton/zio-magic#45]
Currently `zio-magic` brings test dependencies into main class path - including `zio-test` and `zio-test-sbt`. Avoiding this  requires excluding transitive dependencies in sbt. So it looks to be a good idea to move all `ZSpecProvide*` extensions to separate module like `zio-magic-test`

**Comment by kitlangton** [comment]
Great point. I can pull that out :-)

**Comment by kubukoz** [comment]
I'm gonna miss the "magic" word, just look at how glorious the issue titles are.

**Comment by kitlangton** [comment]
`zio-business-synergy` is the new name.

**Comment by kitlangton** [comment]
I don't think I'll get around to this for `zio-magic`, however it's all properly extracted in `ZIO 2.0` (which has some milestones released).
