### ISSUE TITLE
Subtyping issue

### ISSUE THREAD

**Issue by narma** [kitlangton/zio-magic#6]
Hey Kit! Awesome project! 

I faced with following issue, see scastie for example https://scastie.scala-lang.org/narma/qgHyrr4dSKmPnDaRPKTiYg/12

Without zio-magic (using native zio `>>>`, `++` and so on) it works normally without `asInstanceOf`.
Issue is zio-magic doesn't correctly handling subtyping of resulting layer.

`Database.fromDatasourceAndErrorStrategies` returns 
```scala
type Database = Has[Dbs]
abstract class DatabaseModuleBase[Connection, Dbs <: DatabaseOps.ServiceOps[Connection] : Tag]
```

but service requires 
```scala
type Service = DatabaseOps.ServiceOps[Connection]
```

Currently I'm using workaround with `.asInstanceOf`

**Comment by kitlangton** [comment]
Thanks @narma! I'd suspected there may be some difficulties w/ parameterized types and subtyping. This is example is awesome to have! I'll take a look and see what I can do :) Definitely don't want to have users need to call `asInstanceOf`, though I'm glad it works temporarily.

**Comment by kitlangton** [comment]
@narma Pushing version `0.1.5` right now! Fixes it on my end, but I'll keep this open until you can confirm :)

**Comment by narma** [comment]
Confirmed! Thanks! :)
