### ISSUE TITLE
Incorrect partial dependencies order

### ISSUE THREAD

**Issue by vladimirkl** [kitlangton/zio-magic#63]
I found that `injectSome` behaves differentially from `provideSomeLayer` when overriding some of dependencies. This is rare scenario, but it can be useful in tests. Here is spec illustrating the issue:

```
import zio.test._
import zio.test.Assertion._
import zio._
import zio.magic._

object LayerOverrideSpec extends DefaultMutableRunnableSpec {
  type A = Has[A.Service]
  object A {
    trait Service {
      def a: String
    }
    val live: ULayer[A] = ZLayer.succeed(new Service {
      val a = "a"
    })
  }

  type B = Has[B.Service]
  object B {
    trait Service {
      def b: String
    }
    val live1: ULayer[B] = ZLayer.succeed(new Service {
      val b = "b1"
    })

    val live2: ULayer[B] = ZLayer.succeed(new Service {
      val b = "b2"
    })
  }

  type C = Has[C.Service]
  object C {
    trait Service {
      def c: String
    }
    val live: URLayer[A with B, C] =
      ZIO
        .mapN(ZIO.service[A.Service], ZIO.service[B.Service]) { (a, b) =>
          new Service {
            val c = a.a + b.b
          }
        }
        .toLayer
  }

  testM("provideSomeLayer") {
    ZIO
      .service[C.Service]
      .map(x => assert(x.c)(equalTo("ab2")))
      .provideSomeLayer[A with B]((ZLayer.requires[A] ++ B.live2) >>> C.live)
      .provideLayer(A.live ++ B.live1)
  }

  testM("injectSome") {
    ZIO
      .service[C.Service]
      .map(x => assert(x.c)(equalTo("ab2"))) // failed: returns ab1
      .injectSome[A with B](B.live2, C.live)
      .provideLayer(A.live ++ B.live1)
  }
}
```

**Comment by kitlangton** [comment]
Thanks for this example! I'll try and get to the bottom of it 😄

**Comment by kitlangton** [comment]
Ah, just messed around with this (thanks again for the copy-pastable test). The new version `0.3.0` will actually error:

```scala
  ZLayer Wiring Error  

❯ zio.magic.LayerOverrideSpec.B.Service is provided by multiple layers:
❯ — ZLayer.requires[zio.magic.LayerOverrideSpec.A with zio.magic.LayerOverrideSpec.B]
❯ — B.live2
```

The message can probably be a bit clearer, but there's a new error emitted when multiple versions of the same layer are provided, which would happen in the implementation of both provideSome and injectSome, so I think this is correct.

**Comment by vladimirkl** [comment]
Does it mean that dependency override will stop working at all? Actually there is no multiple versions here - we just override one version with another. Same as simply `B.live1 ++ B.live2` which returns only `B.live2`

**Comment by kitlangton** [comment]
It's still possible to override, but in the case of this:

```scala
      .injectSome[A with B](B.live2, C.live)
```
There's basically no point in providing B.live2, because it's going to be overridden later on. Not sure if that makes sense. But you can still do `(ZLayer.requires[A] ++ B.live2) >>> C.live` with inject.
