### ISSUE TITLE
Unused layers

### ISSUE THREAD

**Issue by RicoGit** [kitlangton/zio-magic#66]
Is it possible to fail compilation or issue a warning when some of the provided layers are unused?
The case when I added a redundant layer to wiring or one of the layers not needed anymore etc.

I saw `local val layer$macro$20 in value layer is never used` but it's quite optimistic sometimes.
I mean there are many false-positive cases when unused layers exist, but the wiring is ok.

**Comment by kitlangton** [comment]
Oh, I actually just added that feature in `0.3.0`. (Though there is a chance that this could pop up anyhow, perhaps). 
Have you tried running this with the newest release?

**Comment by RicoGit** [comment]
I've double check, works fine for all my cases, thanks a lot!

**Comment by kitlangton** [comment]
> I've double check, works fine for all my cases, thanks a lot!

Woo hoo! That was great timing 😄

**Comment by kitlangton** [comment]
I actually wasn't sure if I was making the right API decision, so I'm glad to some post-hoc validation😉

**Comment by joroKr21** [comment]
What about a unit layer? Sometimes it's "used" for the side effect.
