### ISSUE TITLE
Scala 2.11 and Scala 2.12 support

### ISSUE THREAD

**Issue by DamianReeves** [kitlangton/zio-magic#7]
Is it possible to add these platforms too?

**Comment by chaitanyawaikar** [comment]
Do we want to add the some kind of mapping between sbt versions and scala versions ?
For example :-
ScalaVersion => Sbt Version
"2.10" => "0.13.18"
"2.12" => "1.2.8"

Or just simply cross version compatibility ?

**Comment by kitlangton** [comment]
@chaitanyawaikar I believe just cross-version support. Unless the sbt will matter as well—I'm not too experienced w/ the pleasures of cross-building :)

**Comment by chaitanyawaikar** [comment]
I can pick this issue and try to add this compatibility.

**Comment by kitlangton** [comment]
@chaitanyawaikar Ah! Thank you so much howeverrr... I actually just got this to work!

**Comment by kitlangton** [comment]
I did have to mangle some code though. I'll push up my changes :) If you'd like to take a look at the commit see if I've royally messed something up :)

**Comment by chaitanyawaikar** [comment]
Sure, you can let me know the branch name, I can review it :)

**Comment by kitlangton** [comment]
@chaitanyawaikar ... `master` hahaha. Since I was just going solo for a while there, I was being a bit lazy w/ proper branch-form ;)
https://github.com/kitlangton/zio-magic/commit/088d23e4d20d71db743e22ea82513be58be88f64

**Comment by kitlangton** [comment]
Done! `0.1.7` is released. Let me know if this doesn't work for ya @DamianReeves and we'll reopen it :)
