### ISSUE TITLE
Scala 3 support

### ISSUE THREAD

**Issue by heksesang** [kitlangton/zio-magic#78]
It would be nice with a Scala 3 release of this library. :)

**Comment by kitlangton** [comment]
I've actually implemented Scala 3 support—only that it's merged into the 2.0 branch of ZIO. I may be a bit too busy to back-port it to this library. The plan is to deprecate this lib once ZIO 2 is released (hoping for August?).

**Comment by kitlangton** [comment]
But you—or anyone—is free to copy-pasta the implementation from there. There's just a lot of overhead maintaining all these versions of the same code 😄

**Comment by heksesang** [comment]
If ZIO 2.0 releases in August, it should be fine for my use case. I don’t think I will be able to port our project to Scala 3 before that. And if the code can be copy-pasted from the ZIO 2.0 branch, I should be able to make a working solution until ZIO 2.0 releases if the release takes longer. :)

**Comment by kitlangton** [comment]
Thanks for understanding @heksesang :)
