### ISSUE TITLE
Support MutableRunnableSpec

### ISSUE THREAD

**Issue by narma** [kitlangton/zio-magic#8]
Hey again, Kit! 

I see that `RunnableSpec` is supported, by new shiny one `MutableRunnableSpec` not supported yet (directly).

It will requires zio >= 1.0.4, not problem for me, but I can say for me only.

WDYT?

**Comment by kitlangton** [comment]
Oh! Didn’t even realize that was a thing! I’ll check it out :) I think it’s reasonable to support all the spec types. Shouldn’t be difficult.

**Comment by narma** [comment]
I see, indeed, it's not an easy one :) So, I started using `ZLayer.fromMagic` and happy with it, still much simpler than the usual way :)

**Comment by kitlangton** [comment]
@narma Glad there's some improvement there ;) 
Meanwhile, I'll keep this issue open and let it gestate in the old subconscious—good luck, brain!

**Comment by kitlangton** [comment]
Gonna close this one for now :) 
I think just `ZLayer.wire` is the ticket, as you've described :)
