### ISSUE TITLE
Scala 3 support

### ISSUE THREAD

**Issue by ex0ns** [kitlangton/zio-magic#97]
Hello

Will this lib be updated with Scala 3 support ? Or should we wait for ZIO 2.0 that will include both zio-magic features and Scala 3 support ?

Thanks

**Comment by kitlangton** [comment]
Currently, Scala 3 support is implemented in the `series/2.x` branch of ZIO. But yeah, to minimize the combinatoric explosion of maintenance efforts, I've so far been procrastinating until that is released :)

**Comment by ex0ns** [comment]
Thanks, that definitely makes sense, in the meantime maybe that it could work by using the 

```
withDottyCompat(scalaVersion())
```

In mill, or something similare with SBT, in order to use 2.13 lib in Scala 3.
I think you can close this issue

**Comment by kitlangton** [comment]
Ah, due to this library's macro-based nature, I don't think that will work. I'm going to look into possibly opening the zio-magic features into `ZIO 1.0`, technically the should work. I just have to be careful around maintaining bin-compat for whatever decisions are made once introduced.
